# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DLockamy's House of Bits
email: dlockamy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of my current programming projects that tend to focus on web services and experimental OS concepts. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dlockamy.com" # the base hostname & protocol for your site
twitter_username: fuciferdesign
github_username:  dlockamy

# Build settings
markdown: kramdown
